### ISSUE TITLE
Adjust tt_store:find_by_time/2 to the new API description

### ISSUE THREAD

**Issue by mentels** [lambdaacademy/2015.12_erlang#6]
tt_store:find_by_time/2 is for getting a list of talks that are **planned to start** in a given time range. Not to return talks that **fit the time range**.

The following tests reveal the problem:
- https://github.com/lambdaacademy/2015.12_erlang/blob/master/test/tt_store_SUITE.erl#L63
- https://github.com/lambdaacademy/2015.12_erlang/blob/master/test/tt_store_SUITE.erl#L69

**Comment by kklocek** [comment]
Fixed.
