### ISSUE TITLE
Fix test/tt_store_SUITE to use EUnit assertions

### ISSUE THREAD

**Issue by mentels** [lambdaacademy/2015.12_erlang#9]
It's better to use EUnit assertion macros in comparison to plain pattern matching. It is because the assertions produce nice output on test failure. See an example [here](https://github.com/lambdaacademy/2015.12_erlang/blob/master/test/tt_importer_SUITE.erl).

[EUnit assertion macros documentation](http://erlang.org/doc/apps/eunit/chapter.html#Assert_macros)

**Comment by kklocek** [comment]
Fixed.
